export const PLAYFIELD_ADD_CARD = 'PLAYFIELD_ADD_CARD';
export const PLAYFIELD_REMOVE_CARD = 'PLAYFIELD_REMOVE_CARD';
export const PLAYFIELD_TOGGLE_TAP = 'PLAYFIELD_TOGGLE_TAP';
export const PLAYFIELD_SHOW_BIG_IMG = 'PLAYFIELD_SHOW_BIG_IMG';
export const PLAYFIELD_UPDATE_CARD = 'PLAYFIELD_UPDATE_CARD';
export const SHUFFLE_DECK = 'SHUFFLE_DECK';
export const PLAYFIELD_TOP_CARD_TO_BOT = 'PLAYFIELD_TOP_CARD_TO_BOT';